groups:
- name: leftovers
  jobs:
  - build-release

resources:
- name: leftovers
  type: git
  source:
    branch: master
    uri: https://github.com/genevieve/leftovers.git

- name: release
  type: github-release
  source:
    owner: genevieve
    repository: leftovers
    access_token: ((leftovers_access_token))

jobs:
- name: build-release
  plan:
  - in_parallel:
    - get: release
    - get: leftovers
  - task: build-release-with-minor-bump
    file: leftovers/ci/tasks/build-release/task.yml
  - put: release
    params:
      name: builds/name
      tag: builds/name
      commitish: builds/commitish
      globs:
      - builds/bin/leftovers-*
