#!/bin/bash -exu

ROOT="${PWD}"

mkdir -p "${GOPATH}/src/github.com/genevieve"

pushd "${GOPATH}/src/github.com/genevieve" > /dev/null
  ln -s "${ROOT}/leftovers"

  ./leftovers/scripts/test acceptance
popd > /dev/null
