name: bump brew tap

on:
  release:
    types: [created]

jobs:
  bump:
    name: Bump homebrew tap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout leftovers repo
        uses: actions/checkout@v2

      - name: Checkout brew tap repo
        uses: actions/checkout@v2
        with:
          repository: genevieve/homebrew-tap
          ssh-key: ${{ secrets.HOMEBREW_TAP_SSH_KEY }}

      - name: Get release version and save to env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Update formula
        run: .github/bump-brew-tap.sh
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
